version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: budget_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: jandaia@masterkey
      POSTGRES_DB: budget_data
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - budget_net

  n8n:
    image: n8nio/n8n:latest
    container_name: budget_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=budget_data
      - DB_POSTGRESDB_USER=user_admin
      - DB_POSTGRESDB_PASSWORD=jandaia@masterkey
      - N8N_ENCRYPTION_KEY=uma_chave_aleatoria_aqui
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - budget_net

  metabase:
    image: metabase/metabase:latest
    container_name: budget_metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=budget_data
      - MB_DB_PORT=5432
      - MB_DB_USER=user_admin
      - MB_DB_PASS=jandaia@masterkey
      - MB_DB_HOST=db
    volumes:
      - ./metabase_data:/metabase-data
    depends_on:
      - db
    networks:
      - budget_net

networks:
  budget_net:
    driver: bridge